In [4]:
import pandas as pd
import os
import glob

In [ ]:
import os
import glob
import pandas as pd
from sqlalchemy import create_engine

# vars is in .env file

engine = create_engine(f'postgresql://{os.getenv("DB_USER")}:{os.getenv("DB_PASSWORD")}@{os.getenv("DB_HOST")}:{os.getenv("DB_PORT")}/{os.getenv("DB_NAME")}')


csv_files = glob.glob("*.csv")

for file_path in csv_files:
    file_name = os.path.basename(file_path)
    table_name = os.path.splitext(file_name)[0]
    
    print(f"جاري رفع {file_name} إلى الجدول {table_name}...")
    
    df = pd.read_csv(file_path)
    df.to_sql(
        name=table_name, 
        con=engine, 
        if_exists='replace', 
        index=False
    )
    print(f"تم بنجاح! ({len(df)} سطر)")

print("\nاكتمل رفع كافة البيانات.")

جاري رفع olist_customers_dataset.csv إلى الجدول olist_customers_dataset...
تم بنجاح! (99441 سطر)
جاري رفع olist_geolocation_dataset.csv إلى الجدول olist_geolocation_dataset...
تم بنجاح! (1000163 سطر)
جاري رفع olist_orders_dataset.csv إلى الجدول olist_orders_dataset...
تم بنجاح! (99441 سطر)
جاري رفع olist_order_items_dataset.csv إلى الجدول olist_order_items_dataset...
تم بنجاح! (112650 سطر)
جاري رفع olist_order_payments_dataset.csv إلى الجدول olist_order_payments_dataset...
تم بنجاح! (103886 سطر)
جاري رفع olist_order_reviews_dataset.csv إلى الجدول olist_order_reviews_dataset...
تم بنجاح! (99224 سطر)
جاري رفع olist_products_dataset.csv إلى الجدول olist_products_dataset...
تم بنجاح! (32951 سطر)
جاري رفع olist_sellers_dataset.csv إلى الجدول olist_sellers_dataset...
تم بنجاح! (3095 سطر)
جاري رفع product_category_name_translation.csv إلى الجدول product_category_name_translation...
تم بنجاح! (71 سطر)

اكتمل رفع كافة البيانات.

In [5]:
for file in glob.glob("data/*.csv"):

    df_name = os.path.splitext(os.path.basename(file))[0]

    globals()[df_name] = pd.read_csv(file)

    print(f"Loaded {file} -> DataFrame '{df_name}'")

Loaded data\olist_customers_dataset.csv -> DataFrame 'olist_customers_dataset'
Loaded data\olist_geolocation_dataset.csv -> DataFrame 'olist_geolocation_dataset'
Loaded data\olist_orders_dataset.csv -> DataFrame 'olist_orders_dataset'
Loaded data\olist_order_items_dataset.csv -> DataFrame 'olist_order_items_dataset'
Loaded data\olist_order_payments_dataset.csv -> DataFrame 'olist_order_payments_dataset'
Loaded data\olist_order_reviews_dataset.csv -> DataFrame 'olist_order_reviews_dataset'
Loaded data\olist_products_dataset.csv -> DataFrame 'olist_products_dataset'
Loaded data\olist_sellers_dataset.csv -> DataFrame 'olist_sellers_dataset'
Loaded data\product_category_name_translation.csv -> DataFrame 'product_category_name_translation'

In [9]:
olist_customers_dataset.duplicated().sum()

np.int64(0)

In [10]:
olist_customers_dataset.isna().sum()

customer_id                 0
customer_unique_id          0
customer_zip_code_prefix    0
customer_city               0
customer_state              0
dtype: int64

In [11]:
olist_customers_dataset.shape

(99441, 5)

In [12]:
olist_customers_dataset

,customer_id,customer_unique_id,customer_zip_code_prefix,customer_city,customer_state
0,06b8999e2fba1a1fbc88172c00ba8bc7,861eff4711a542e4b93843c6dd7febb0,14409,franca,SP
1,18955e83d337fd6b2def6b18a428ac77,290c77bc529b7ac935b93aa66c333dc3,9790,sao bernardo do campo,SP
2,4e7b3e00288586ebd08712fdd0374a03,060e732b5b29e8181a18229c7b0b2b5e,1151,sao paulo,SP
3,b2b6027bc5c5109e529d4dc6358b12c3,259dac757896d24d7702b9acbbff3f3c,8775,mogi das cruzes,SP
4,4f2d8ab171c80ec8364f7c12e35b23ad,345ecd01c38d18a9036ed96c73b8d066,13056,campinas,SP
...,...,...,...,...,...
99436,17ddf5dd5d51696bb3d7c6291687be6f,1a29b476fee25c95fbafc67c5ac95cf8,3937,sao paulo,SP
99437,e7b71a9017aa05c9a7fd292d714858e8,d52a67c98be1cf6a5c84435bd38d095d,6764,taboao da serra,SP
99438,5e28dfe12db7fb50a4b2f691faecea5e,e9f50caf99f032f0bf3c55141f019d99,60115,fortaleza,CE
99439,56b18e2166679b8a959d72dd06da27f9,73c2643a0a458b49f58cea58833b192e,92120,canoas,RS
99440,274fa6071e5e17fe303b9748641082c8,84732c5050c01db9b23e19ba39899398,6703,cotia,SP

In [13]:
olist_sellers_dataset

,seller_id,seller_zip_code_prefix,seller_city,seller_state
0,3442f8959a84dea7ee197c632cb2df15,13023,campinas,SP
1,d1b65fc7debc3361ea86b5f14c68d2e2,13844,mogi guacu,SP
2,ce3ad9de960102d0677a81f5d0bb7b2d,20031,rio de janeiro,RJ
3,c0f3eea2e14555b6faeea3dd58c1b1c3,4195,sao paulo,SP
4,51a04a8a6bdcb23deccc82b0b80742cf,12914,braganca paulista,SP
...,...,...,...,...
3090,98dddbc4601dd4443ca174359b237166,87111,sarandi,PR
3091,f8201cab383e484733266d1906e2fdfa,88137,palhoca,SC
3092,74871d19219c7d518d0090283e03c137,4650,sao paulo,SP
3093,e603cf3fec55f8697c9059638d6c8eb5,96080,pelotas,RS
3094,9e25199f6ef7e7c347120ff175652c3b,12051,taubate,SP

In [14]:
product_category_name_translation

            product_category_name product_category_name_english
0                    beleza_saude                 health_beauty
1          informatica_acessorios         computers_accessories
2                      automotivo                          auto
3                 cama_mesa_banho                bed_bath_table
4                moveis_decoracao               furniture_decor
..                            ...                           ...
66                         flores                       flowers
67             artes_e_artesanato         arts_and_craftmanship
68                fraldas_higiene           diapers_and_hygiene
69  fashion_roupa_infanto_juvenil     fashion_childrens_clothes
70             seguros_e_servicos         security_and_services

[71 rows x 2 columns]

In [15]:
olist_order_items_dataset

,order_id,order_item_id,product_id,seller_id,shipping_limit_date,price,freight_value
0,00010242fe8c5a6d1ba2dd792cb16214,1,4244733e06e7ecb4970a6e2683c13e61,48436dade18ac8b2bce089ec2a041202,2017-09-19 09:45:35,58.90,13.29
1,00018f77f2f0320c557190d7a144bdd3,1,e5f2d52b802189ee658865ca93d83a8f,dd7ddc04e1b6c2c614352b383efe2d36,2017-05-03 11:05:13,239.90,19.93
2,000229ec398224ef6ca0657da4fc703e,1,c777355d18b72b67abbeef9df44fd0fd,5b51032eddd242adc84c38acab88f23d,2018-01-18 14:48:30,199.00,17.87
3,00024acbcdf0a6daa1e931b038114c75,1,7634da152a4610f1595efa32f14722fc,9d7a1d34a5052409006425275ba1c2b4,2018-08-15 10:10:18,12.99,12.79
4,00042b26cf59d7ce69dfabb4e55b4fd9,1,ac6c3623068f30de03045865e4e10089,df560393f3a51e74553ab94004ba5c87,2017-02-13 13:57:51,199.90,18.14
...,...,...,...,...,...,...,...
112645,fffc94f6ce00a00581880bf54a75a037,1,4aa6014eceb682077f9dc4bffebc05b0,b8bc237ba3788b23da09c0f1f3a3288c,2018-05-02 04:11:01,299.99,43.41
112646,fffcd46ef2263f404302a634eb57f7eb,1,32e07fd915822b0765e448c4dd74c828,f3c38ab652836d21de61fb8314b69182,2018-07-20 04:31:48,350.00,36.53
112647,fffce4705a9662cd70adb13d4a31832d,1,72a30483855e2eafc67aee5dc2560482,c3cfdc648177fdbbbb35635a37472c53,2017-10-30 17:14:25,99.90,16.95
112648,fffe18544ffabc95dfada21779c9644f,1,9c422a519119dcad7575db5af1ba540e,2b3e4a2a3ea8e01938cabda2a3e5cc79,2017-08-21 00:04:32,55.99,8.72
112649,fffe41c64501cc87c801fd61db3f6244,1,350688d9dc1e75ff97be326363655e01,f7ccf836d21b2fb1de37564105216cc1,2018-06-12 17:10:13,43.00,12.79

In [16]:
olist_order_payments_dataset

,order_id,payment_sequential,payment_type,payment_installments,payment_value
0,b81ef226f3fe1789b1e8b2acac839d17,1,credit_card,8,99.33
1,a9810da82917af2d9aefd1278f1dcfa0,1,credit_card,1,24.39
2,25e8ea4e93396b6fa0d3dd708e76c1bd,1,credit_card,1,65.71
3,ba78997921bbcdc1373bb41e913ab953,1,credit_card,8,107.78
4,42fdf880ba16b47b59251dd489d4441a,1,credit_card,2,128.45
...,...,...,...,...,...
103881,0406037ad97740d563a178ecc7a2075c,1,boleto,1,363.31
103882,7b905861d7c825891d6347454ea7863f,1,credit_card,2,96.80
103883,32609bbb3dd69b3c066a6860554a77bf,1,credit_card,1,47.77
103884,b8b61059626efa996a60be9bb9320e10,1,credit_card,5,369.54
103885,28bbae6599b09d39ca406b747b6632b1,1,boleto,1,191.58

In [35]:
# Aggregate before you join — order items and payments have many rows per order
olist_order_items_agg = olist_order_items_dataset.groupby('order_id').agg({'order_item_id': 'count', 'price': 'sum'})

In [36]:
olist_order_items_agg

                                  order_item_id   price
order_id
00010242fe8c5a6d1ba2dd792cb16214              1   58.90
00018f77f2f0320c557190d7a144bdd3              1  239.90
000229ec398224ef6ca0657da4fc703e              1  199.00
00024acbcdf0a6daa1e931b038114c75              1   12.99
00042b26cf59d7ce69dfabb4e55b4fd9              1  199.90
...                                         ...     ...
fffc94f6ce00a00581880bf54a75a037              1  299.99
fffcd46ef2263f404302a634eb57f7eb              1  350.00
fffce4705a9662cd70adb13d4a31832d              1   99.90
fffe18544ffabc95dfada21779c9644f              1   55.99
fffe41c64501cc87c801fd61db3f6244              1   43.00

[98666 rows x 2 columns]